import {
    IconAlertTriangle,
    IconArrowsExchange,
    IconBottle,
    IconBuildingStore,
    IconBuildingWarehouse,
    IconChartBar,
    IconChartHistogram,
    IconClipboardData,
    IconComponents,
    IconCreditCardPay,
    IconCreditCardRefund,
    IconDatabase,
    IconFileAnalytics,
    IconLayoutDashboard,
    IconLayoutGrid,
    IconPackageImport,
    IconPackages,
    IconReceipt2,
    IconReportAnalytics,
    IconShieldLock,
    IconSettings,
    IconShoppingBag,
    IconTag,
    IconTruckDelivery,
    IconUserCog,
    IconUserDollar,
    IconUsersGroup,
    IconTool,
} from "@tabler/icons-react";

export const menuAdmin = [
    {
        label: "Dasbor",
        icon: IconLayoutDashboard,
        href: "/admin/dashboard",
        accessKey: "dashboard",
    },
    {
        label: "Master Data",
        icon: IconDatabase,
        children: [
            {
                label: "Brand",
                icon: IconTag,
                href: "/admin/master/brand",
                accessKey: "master-brand",
            },
            {
                label: "Barang Bibit",
                icon: IconPackages,
                href: "/admin/barang-bibit",
                accessKey: "barang-bibit",
            },
            {
                label: "Gudang",
                icon: IconBuildingWarehouse,
                href: "/admin/master/gudang",
                accessKey: "master-gudang",
            },
            {
                label: "Supplier",
                icon: IconTruckDelivery,
                href: "/admin/master/supplier",
                accessKey: "master-supplier",
            },
            {
                label: "Customer",
                icon: IconUsersGroup,
                href: "/admin/master/customer",
                accessKey: "master-customer",
            },
            {
                label: "Sales",
                icon: IconUserDollar,
                href: "/admin/master/sales",
                accessKey: "master-sales",
            },
            {
                label: "Botol Kemasan",
                icon: IconBottle,
                href: "/admin/master/botol",
                accessKey: "master-botol",
            },
            {
                label: "Botol Kosong",
                icon: IconBottle,
                href: "/admin/master/botol-kosong",
                accessKey: "master-botol",
            },
            {
                label: "Users",
                icon: IconUserCog,
                href: "/admin/users",
                accessKey: "users",
            },
            {
                label: "Hak Akses User",
                icon: IconShieldLock,
                href: "/admin/users-access",
                accessKey: "user-access",
            },

        ],
    },
    {
        label: "Inventory",
        icon: IconBuildingWarehouse,
        children: [
            {
                label: "Stok Gudang",
                icon: IconPackages,
                href: "/admin/stok-gudang",
                accessKey: "stok-gudang",
            },
            {
                label: "Mutasi Stok",
                icon: IconArrowsExchange,
                href: "/admin/mutasi-stok",
                accessKey: "mutasi-stok",
            },
            {
                label: "Stok Menipis",
                icon: IconAlertTriangle,
                href: "/admin/stok-menipis",
                accessKey: "stok-menipis",
            },
        ],
    },
    {
        label: "Transaksi",
        icon: IconReceipt2,
        children: [
            {
                label: "Pembelian Supplier",
                icon: IconPackageImport,
                href: "/admin/pembelian",
                accessKey: "pembelian",
            },
            {
                label: "Penjualan Retail",
                icon: IconShoppingBag,
                href: "/admin/penjualan/retail",
                accessKey: "penjualan-retail",
            },
            {
                label: "Penjualan Sales",
                icon: IconBuildingStore,
                href: "/admin/penjualan/sales",
                accessKey: "penjualan-grosir",
            },
            {
                label: "Penjualan Botol Kosong",
                icon: IconBottle,
                href: "/admin/penjualan-botol-kosong",
                accessKey: "penjualan-retail",
            },
            {
                label: "Hutang Supplier",
                icon: IconCreditCardPay,
                href: "/admin/hutang",
                accessKey: "hutang",
            },
            {
                label: "Piutang Customer",
                icon: IconCreditCardRefund,
                href: "/admin/piutang",
                accessKey: "piutang",
            },
            {
                label: "Piutang Supplier",
                icon: IconCreditCardRefund,
                href: "/admin/piutang-supplier",
                accessKey: "piutang-supplier",
            },

            {
                label: "Uang Kas",
                icon: IconReceipt2,
                href: "/admin/kas",
                accessKey: "kas",
            },
        ],
    },
    {
        label: "Riwayat Transaksi",
        icon: IconClipboardData,
        children: [
            {
                label: "Lihat Pembelian Supplier",
                icon: IconPackageImport,
                href: "/admin/riwayat-pembelian",
                accessKey: "riwayat-pembelian",
            },
            {
                label: "Lihat Penjualan",
                icon: IconShoppingBag,
                href: "/admin/riwayat-penjualan/retail",
                accessKey: "riwayat-penjualan",
            },
        ],
    },
    {
        label: "Laporan",
        icon: IconReportAnalytics,
        children: [
            {
                label: "Pembelian Supplier",
                icon: IconFileAnalytics,
                href: "/admin/laporan/pembelian",
                accessKey: "laporan-pembelian",
            },
            {
                label: "Penjualan",
                icon: IconChartBar,
                href: "/admin/laporan/penjualan",
                accessKey: "laporan-penjualan",
            },
            {
                label: "Stok",
                icon: IconPackages,
                href: "/admin/laporan/stok",
                accessKey: "laporan-stok",
            },
            {
                label: "Mutasi Stok",
                icon: IconArrowsExchange,
                href: "/admin/laporan/mutasi-stok",
                accessKey: "laporan-mutasi-stok",
            },
            {
                label: "Barang Summary",
                icon: IconClipboardData,
                href: "/admin/laporan/barang-summary",
                accessKey: "laporan-barang-summary",
            },
            {
                label: "Hutang Supplier",
                icon: IconCreditCardPay,
                href: "/admin/laporan/hutang",
                accessKey: "laporan-hutang",
            },
            {
                label: "Piutang Customer",
                icon: IconCreditCardRefund,
                href: "/admin/laporan/piutang",
                accessKey: "laporan-piutang",
            },
            {
                label: "Piutang Supplier",
                icon: IconCreditCardRefund,
                href: "/admin/laporan/piutang-supplier",
                accessKey: "laporan-piutang-supplier",
            },

            {
                label: "Kas",
                icon: IconReceipt2,
                href: "/admin/laporan/kas",
                accessKey: "laporan-kas",
            },
            {
                label: "Laba Kotor",
                icon: IconChartHistogram,
                href: "/admin/laporan/laba-kotor",
                accessKey: "laporan-laba-kotor",
            },
        ],
    },
    {
        label: "Utility",
        icon: IconTool,
        children: [
            {
                label: "Setting System",
                icon: IconSettings,
                href: "/admin/setting-system",
                accessKey: "setting-system",
            },
            {
                label: "Setting Nota",
                icon: IconReceipt2,
                href: "/admin/setting-nota",
                accessKey: "setting-nota",
            },
            {
                label: "Tutup Toko",
                icon: IconBuildingStore,
                href: "/admin/utility",
                accessKey: "utility",
            },
        ],
    },

];
